CREATE TABLE films
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    filmtype    VARCHAR(255),
    description VARCHAR(255),
    summary     TEXT,
    img_url     VARCHAR(255),
    CONSTRAINT pk_films PRIMARY KEY (id)
);